// The domain-schema generator (ADR 0011) — pure, no DB. The EXACT-STRING snapshots
// below pin the security-critical PERMISSIONS clauses byte-for-byte: any deviation is
// a semantics change and must be a conscious, reviewed decision (a new ADR), never an
// accidental refactor. The live proof is test/enforcement.test.ts (cleo/ben/ada).

import { describe, test, expect } from "bun:test";
import { domainSchema } from "../src/graph/domain.ts";
import { exampleDefinition } from "../fixtures/example/graph.ts";
import type { Definition } from "../src/provider/types.ts";

const base = (buckets: Definition["buckets"]): Definition => ({
  namespace: "t", ambient: { skills: [] }, purposes: [], buckets,
  toolCatalog: {}, skillCatalog: {}, agentByPurpose: {}, marketplaces: {},
});

describe("domainSchema", () => {
  test("scoped bucket — the exact template (client, rowScope: account)", () => {
    const [ddl] = domainSchema(base([
      { id: "clients", backend: "surreal", tables: ["client"], owner: "success", rowScope: "account", sens: "high" },
    ]));
    expect(ddl).toBe(
      `-- generated by merovingian (ADR 0011) — bucket "clients"; regenerated on every apply, do not hand-edit\n` +
      `DEFINE TABLE OVERWRITE client SCHEMALESS\n` +
      `  PERMISSIONS\n` +
      `    FOR select WHERE\n` +
      `      account IN $auth->responsible.scope\n` +
      `      OR $auth->responsible[WHERE scope = NONE]->purpose CONTAINSANY bucket:⟨clients⟩.owner.lineage\n` +
      `    FOR create, update, delete NONE;\n` +
      `DEFINE FIELD OVERWRITE account ON client TYPE option<string>;`,
    );
  });

  test("unscoped bucket — lineage clause only, no field define", () => {
    const [ddl] = domainSchema(base([
      { id: "proposals", backend: "surreal", tables: ["proposal"], owner: "sales", sens: "high" },
    ]));
    expect(ddl).toBe(
      `-- generated by merovingian (ADR 0011) — bucket "proposals"; regenerated on every apply, do not hand-edit\n` +
      `DEFINE TABLE OVERWRITE proposal SCHEMALESS\n` +
      `  PERMISSIONS\n` +
      `    FOR select WHERE\n` +
      `      $auth->responsible[WHERE scope = NONE]->purpose CONTAINSANY bucket:⟨proposals⟩.owner.lineage\n` +
      `    FOR create, update, delete NONE;`,
    );
  });

  test("hyphenated bucket ids are legal (⟨⟩-escaped record id)", () => {
    const [ddl] = domainSchema(base([
      { id: "faturamento-e-financas", backend: "surreal", tables: ["invoice"], owner: "fin", sens: "high" },
    ]));
    expect(ddl).toContain("bucket:⟨faturamento-e-financas⟩.owner.lineage");
  });

  test("one statement block per table, Definition order; okf buckets skipped", () => {
    const out = domainSchema(base([
      { id: "kb", backend: "okf-repo", repo: "o/r", owner: "p", sens: "low" },
      { id: "clients", backend: "surreal", tables: ["client", "contact"], owner: "success", rowScope: "account", sens: "high" },
    ]));
    expect(out.length).toBe(2);
    expect(out[0]).toContain("DEFINE TABLE OVERWRITE client ");
    expect(out[1]).toContain("DEFINE TABLE OVERWRITE contact ");
  });

  test("the acme fixture generates 3 blocks (client, contact, proposal)", () => {
    const out = domainSchema(exampleDefinition);
    expect(out.map((d) => d.match(/DEFINE TABLE OVERWRITE (\w+)/)![1]).sort()).toEqual(["client", "contact", "proposal"]);
  });

  test("defense in depth — unsafe identifiers throw even if validate was skipped", () => {
    expect(() => domainSchema(base([
      { id: "x", backend: "surreal", tables: ["bad-table"], owner: "p", sens: "low" },
    ]))).toThrow(/unsafe table name/);
    expect(() => domainSchema(base([
      { id: "x", backend: "surreal", tables: ["t"], owner: "p", rowScope: "a b", sens: "low" },
    ]))).toThrow(/unsafe rowScope/);
    expect(() => domainSchema(base([
      { id: "x⟩; REMOVE TABLE user", backend: "surreal", tables: ["t"], owner: "p", sens: "low" },
    ]))).toThrow(/unsafe bucket id/);
    expect(() => domainSchema(base([
      { id: "x", backend: "surreal", tables: ["user"], owner: "p", sens: "low" },
    ]))).toThrow(/reserved/);
  });
});
