import type { Artifact, Degradation, PreparedProjection } from "./artifacts.ts";
import { buildMcp, type McpJson, type SurrealAccess } from "./emit-claude.ts";
import { buildWorkspaceInstructions } from "./render-instructions.ts";
import type { Manifest, ToolMount } from "./resolve.ts";

const tomlString = (value: string): string => JSON.stringify(value);
const tomlArray = (values: string[]): string => `[${values.map(tomlString).join(", ")}]`;
const tableKey = (value: string): string => tomlString(value);

function splitPluginId(id: string): { plugin: string; marketplace: string } {
  const at = id.lastIndexOf("@");
  return { plugin: id.slice(0, at), marketplace: id.slice(at + 1) };
}

function companyEnv(m: Manifest, mount: ToolMount): Record<string, string> {
  if (mount.keySource !== "company") return mount.env;
  const env: Record<string, string> = {};
  for (const [key, ref] of Object.entries(mount.env)) {
    const sourceName = ref.match(/^\$\{(.+)\}$/)?.[1];
    const value = sourceName ? m.toolEnv[sourceName] : undefined;
    if (value !== undefined) env[key] = value;
  }
  return env;
}

function renderMcp(
  name: string,
  server: McpJson["mcpServers"][string],
  envOverride?: Record<string, string>,
): string[] {
  const lines = [`[mcp_servers.${tableKey(name)}]`];
  if ("type" in server) {
    lines.push(`url = ${tomlString(server.url)}`);
  } else {
    lines.push(`command = ${tomlString(server.command)}`);
    if (server.args.length) lines.push(`args = ${tomlArray(server.args)}`);
    const env = envOverride ?? server.env;
    if (Object.keys(env).length) {
      lines.push("");
      lines.push(`[mcp_servers.${tableKey(name)}.env]`);
      for (const key of Object.keys(env).sort()) lines.push(`${tableKey(key)} = ${tomlString(env[key]!)}`);
    }
  }
  return lines;
}

export interface CodexConfigResult {
  content: string;
  degradations: Degradation[];
}

export function buildCodexConfig(m: Manifest, access?: SurrealAccess): CodexConfigResult {
  const degradations: Degradation[] = [];
  const lines = [
    "# Generated by merovingian build. Do not edit by hand.",
    "project_root_markers = []",
    'default_permissions = "merovingian"',
    "",
    "[agents]",
    "enabled = true",
  ];
  for (const agent of [...m.libraryAgents].sort((a, b) => a.name.localeCompare(b.name))) {
    lines.push("");
    lines.push(`[agents.${tableKey(agent.name)}]`);
    lines.push(`description = ${tomlString(agent.description)}`);
    lines.push(`config_file = ${tomlString(`agents/${agent.name}.toml`)}`);
  }
  lines.push(
    "",
    "[permissions]",
    "",
    "[permissions.merovingian]",
    'description = "Merovingian workspace plus read-only projected OKF stores."',
    'extends = ":workspace"',
  );
  if (m.okf.length) {
    lines.push("");
    lines.push("[permissions.merovingian.filesystem]");
    for (const mount of m.okf) lines.push(`${tomlString(mount.path)} = "read"`);
  }

  const mcp = buildMcp(m, access);
  for (const name of Object.keys(mcp.mcpServers).sort()) {
    const server = mcp.mcpServers[name]!;
    if ("type" in server && server.type === "sse") {
      degradations.push({
        builder: "codex",
        capability: "MCP transport",
        resource: name,
        reason: "legacy SSE is not supported; provide a Streamable HTTP endpoint",
      });
      continue;
    }
    const mount = m.toolMounts.find((candidate) => candidate.name === name);
    lines.push("");
    lines.push(...renderMcp(name, server, mount ? companyEnv(m, mount) : undefined));
  }

  for (const id of m.plugins) {
    const { marketplace } = splitPluginId(id);
    if (!m.marketplaces[marketplace]?.codex) {
      degradations.push({
        builder: "codex",
        capability: "plugin",
        resource: id,
        reason: "the logical marketplace has no Codex binding",
      });
    }
  }

  return { content: lines.join("\n") + "\n", degradations };
}

export function buildAgentsMd(m: Manifest, degradations: Degradation[] = []): string {
  return buildWorkspaceInstructions(m, "codex", degradations);
}

function codexAgent(instructions: string): string {
  return [
    "# Generated by merovingian build. Do not edit by hand.",
    `developer_instructions = ${tomlString(instructions)}`,
    "",
  ].join("\n");
}

export function prepareCodex(m: Manifest, access?: SurrealAccess): PreparedProjection {
  const config = buildCodexConfig(m, access);
  const artifacts: Artifact[] = [
    { builder: "codex", path: "AGENTS.md", content: buildAgentsMd(m, config.degradations) },
    { builder: "codex", path: ".codex/config.toml", content: config.content, mode: 0o600 },
  ];
  for (const skill of m.librarySkills) {
    for (const [relative, content] of Object.entries(skill.files)) {
      artifacts.push({ builder: "codex", path: `.agents/skills/${skill.name}/${relative}`, content });
    }
  }
  for (const agent of m.libraryAgents) {
    artifacts.push({
      builder: "codex",
      path: `.codex/agents/${agent.name}.toml`,
      content: codexAgent(agent.instructions),
    });
  }
  return { artifacts, degradations: config.degradations };
}
