// Materialize a Manifest into a workspace folder:
//   CLAUDE.md                  — the index a human/agent reads
//   .mcp.json                  — tools, by name (stub placeholders)
//   .claude/settings.json      — marketplace + plugins + additionalDirectories + env
//   .claude/skills/<name>/…    — library skills, content from the manifest (ADR 0012)
//   .claude/agents/<name>.md   — library agents, content from the manifest (ADR 0012)
//   .merovingian/build.json    — stamp: what built this folder
//
// emit OWNS .claude/skills and .claude/agents wholesale: both are wiped and
// rebuilt from the manifest on every build — a skill you lost access to must not
// survive a rebuild. The workspace is generated by contract ("do not edit by hand").
//
// Shapes verified against a real ~/.claude/settings.json.

import { rm } from "node:fs/promises";
import { join } from "node:path";
import { writeFileAtomic, writeJsonAtomic } from "../fs/atomic.ts";
import { assignmentsLabel, type Manifest } from "./resolve.ts";

/** How the surreal-data MCP gets its token — NO JWT embedded; it fetches per-call
 *  (from the service via gh, or dev-mints with MEROVINGIAN_USER). */
export interface SurrealAccess {
  url: string;
  ns: string;
  db: string;
  /** remote: the build/auth service url (MCP fetches /token with gh) */
  service?: string;
  /** remote: the merovingian namespace */
  namespace?: string;
  /** dev: mint locally as this user */
  user?: string;
}

/** How the emitted .mcp.json invokes the bundled system MCP servers. The .mcp.json
 *  outlives this process and may be committed — it must NEVER carry a path that dies
 *  with a cache or an upgrade. Installed from npm → invoke by PACKAGE NAME (bunx
 *  resolves it, version-agnostic). Running from a checkout (dev) → the CLI bin's
 *  absolute path is stable enough and keeps dev zero-config. */
const NPM_PACKAGE = "@supernova-labs/merovingian";
const CLI_BIN = join(import.meta.dir, "../../bin/merovingian.ts");
const INSTALLED = import.meta.dir.includes("node_modules") || import.meta.dir.includes("/.bun/install/");

function mcpInvocation(
  name: "inbox" | "decisions" | "surreal-data",
  env: Record<string, string>,
): { command: string; args: string[]; env: Record<string, string> } {
  return INSTALLED
    ? { command: "bunx", args: ["--bun", NPM_PACKAGE, "mcp", name], env }
    : { command: "bun", args: ["run", CLI_BIN, "mcp", name], env };
}

/** The token-source env shared by the system MCPs (no JWT — fetched per-call). */
function tokenSourceEnv(m: Manifest, access: SurrealAccess): Record<string, string> {
  return {
    SURREAL_URL: access.url,
    SURREAL_NS: access.ns,
    MEROVINGIAN_DB: access.db,
    ...(access.service
      ? { MEROVINGIAN_SERVICE_URL: access.service, MEROVINGIAN_NAMESPACE: access.namespace ?? m.namespace }
      : { MEROVINGIAN_USER: access.user ?? m.user.id }),
  };
}

/** The settings.json the build writes. */
export interface SettingsJson {
  $schema: string;
  enableAllProjectMcpServers: boolean;
  permissions: { additionalDirectories: string[] };
  env: Record<string, string>;
  extraKnownMarketplaces: Record<string, { source: { source: "github"; repo: string }; autoUpdate: boolean }>;
  enabledPlugins: Record<string, boolean>;
}

export interface McpJson {
  mcpServers: Record<
    string,
    | { command: string; args: string[]; env: Record<string, string> }
    | { type: "http" | "sse"; url: string }
  >;
}

export function buildSettings(m: Manifest): SettingsJson {
  const enabledPlugins: Record<string, boolean> = {};
  for (const p of m.plugins) enabledPlugins[p] = true;

  return {
    $schema: "https://json.schemastore.org/claude-code-settings.json",
    enableAllProjectMcpServers: true,
    permissions: {
      additionalDirectories: m.okf.map((o) => o.path),
    },
    env: {
      MEROVINGIAN_NAMESPACE: m.namespace,
      MEROVINGIAN_USER: m.user.id,
      MEROVINGIAN_TOKEN: `fake-${m.user.id}-token`,
      // resolved company keys (perplexity/grok) — gitignored, injected into every MCP
      ...m.toolEnv,
    },
    extraKnownMarketplaces: Object.fromEntries(
      Object.entries(m.marketplaces).map(([name, repo]) => [
        name,
        { source: { source: "github" as const, repo }, autoUpdate: true },
      ]),
    ),
    enabledPlugins,
  };
}

export function buildMcp(m: Manifest, access?: SurrealAccess): McpJson {
  const mcpServers: McpJson["mcpServers"] = {};
  // pipes from the registry. company keys go to settings.local.json env (not here);
  // .mcp.json is committed-by-convention, so no raw secrets in it. Remote tools
  // (http/sse) emit {type, url} — member auth is Claude Code's per-user OAuth.
  for (const t of m.toolMounts) {
    mcpServers[t.name] =
      t.kind === "stdio"
        ? { command: t.command ?? "echo", args: t.args, env: t.keySource === "company" ? {} : t.env }
        : { type: t.kind, url: t.url ?? "" };
  }
  // system MCPs (no token embedded — they fetch per-call). inbox is ambient
  // (always); surreal-data only when the user has data buckets.
  if (access) {
    // MEROVINGIAN_PURPOSES = the projection's visible purposes — scope-hint
    // affordance for the friction/pending tools (the db enforces, ADR 0014).
    mcpServers["inbox"] = mcpInvocation("inbox", {
      ...tokenSourceEnv(m, access),
      MEROVINGIAN_PURPOSES: JSON.stringify(m.visiblePurposes),
    });
    // decisions is ambient too (ADR 0013): every identity consults jurisprudence and
    // registers in-flight decisions. MEROVINGIAN_DECISION_DOMAINS = affordance only.
    mcpServers["decisions"] = mcpInvocation("decisions", {
      ...tokenSourceEnv(m, access),
      MEROVINGIAN_DECISION_DOMAINS: JSON.stringify(m.decisionDomains),
    });
  }
  if (m.surreal.length && access) {
    // MEROVINGIAN_BUCKETS: the identity's mounts — the MCP's tool surface (ADR 0011).
    // Affordance only; the db enforces.
    mcpServers["surreal-data"] = mcpInvocation("surreal-data", {
      ...tokenSourceEnv(m, access),
      MEROVINGIAN_BUCKETS: JSON.stringify(m.surreal),
    });
  } else if (m.surreal.length) {
    // stub backend: placeholders so the index still reflects the data buckets
    for (const s of m.surreal) {
      mcpServers[`surreal-${s.bucket}`] = {
        command: "echo",
        args: [`stub:surreal:${s.bucket}`],
        env: { TABLES: s.tables.join(","), ...(s.scope ? { SCOPE: s.scope } : {}) },
      };
    }
  }
  return { mcpServers };
}

function buildClaudeMd(m: Manifest): string {
  const lines: string[] = [];
  lines.push(`# ${m.namespace} — workspace of ${m.user.name}`);
  lines.push("");
  lines.push(
    `> Scoped projection generated by \`merovingian build\`. ` +
      `Assignments: **${assignmentsLabel(m.assignments)}**` +
      `. Do not edit by hand — run the build again.`,
  );
  lines.push("");

  lines.push(`## Purposes`);
  lines.push(m.visiblePurposes.map((p) => `\`${p}\``).join(" · "));
  lines.push("");

  lines.push(`## Skills`);
  const skills = [...m.ambientSkills.map((s) => `${s} (ambient)`), ...m.skills];
  lines.push(skills.length ? skills.map((s) => `\`${s}\``).join(" · ") : "_(none)_");
  lines.push("");

  lines.push(`## Tools`);
  lines.push(m.tools.length ? m.tools.map((t) => `\`${t}\``).join(" · ") : "_(none)_");
  lines.push("");

  lines.push(`## Context (okf — mounted via additionalDirectories)`);
  lines.push(m.okf.length ? m.okf.map((o) => `- \`${o.bucket}\` → \`${o.path}\``).join("\n") : "_(none)_");
  lines.push("");

  lines.push(`## Data (surreal — via scoped MCP)`);
  lines.push(
    m.surreal.length
      ? m.surreal
          .map((s) => `- \`${s.bucket}\` [${s.tables.join(", ")}]${s.scope ? ` — scope \`${s.scope}\`` : ""}`)
          .join("\n")
      : "_(none)_",
  );
  lines.push("");

  lines.push(`## Decisions (via the decisions MCP)`);
  lines.push(
    m.decisionDomains.length
      ? `Your decision domains: ${m.decisionDomains.map((d) => `\`${d}\``).join(" · ")}.`
      : `_(no decision domains on your purposes)_`,
  );
  lines.push("");
  lines.push(
    `**Records are law; logs are jurisprudence under construction.** Ratified records ` +
      `(\`search-decisions\`/\`get-decision\`) are universal and binding. In-flight logs you or ` +
      `others registered are NOT policy — never apply one without confirming with your human. ` +
      `When you make a call mid-work that no record covers, \`register-decision\` it (with the ` +
      `records you applied, if any) — governance drains the log and promotes what converges.`,
  );
  lines.push("");

  lines.push(`## Library (materialized into .claude/)`);
  if (m.librarySkills.length || m.libraryAgents.length) {
    if (m.librarySkills.length) lines.push(`- skills: ${m.librarySkills.map((s) => `\`${s.name}\``).join(" · ")} → \`.claude/skills/\``);
    if (m.libraryAgents.length) lines.push(`- agents: ${m.libraryAgents.map((a) => `\`${a.name}\``).join(" · ")} → \`.claude/agents/\``);
  } else {
    lines.push("_(none)_");
  }
  lines.push("");

  lines.push(`## Plugins (external)`);
  lines.push(m.plugins.length ? m.plugins.map((p) => `- \`${p}\``).join("\n") : "_(none)_");
  lines.push("");

  lines.push(`## Marketplaces`);
  const mkts = Object.entries(m.marketplaces);
  lines.push(mkts.length ? mkts.map(([n, r]) => `- \`${n}\` → \`${r}\``).join("\n") : "_(none)_");
  lines.push("");
  return lines.join("\n");
}

export interface EmitResult {
  files: string[];
}

export async function emit(m: Manifest, targetDir: string, access?: SurrealAccess): Promise<EmitResult> {
  // settings.local.json (not settings.json): generated, disposable, carries
  // identity/token — the Claude Code file kept out of git by default.
  const settingsPath = join(targetDir, ".claude", "settings.local.json");
  const mcpPath = join(targetDir, ".mcp.json");
  const claudePath = join(targetDir, "CLAUDE.md");
  const stampPath = join(targetDir, ".merovingian", "build.json");
  const skillsDir = join(targetDir, ".claude", "skills");
  const agentsDir = join(targetDir, ".claude", "agents");

  await writeJsonAtomic(settingsPath, buildSettings(m));
  await writeJsonAtomic(mcpPath, buildMcp(m, access));
  await writeFileAtomic(claudePath, buildClaudeMd(m));

  // library content: wipe + rebuild from the manifest (idempotent; stale content
  // from a narrower rebuild cannot survive).
  await rm(skillsDir, { recursive: true, force: true });
  await rm(agentsDir, { recursive: true, force: true });
  const files: string[] = [claudePath, mcpPath, settingsPath];
  for (const s of m.librarySkills) {
    for (const [rel, content] of Object.entries(s.files)) {
      const p = join(skillsDir, s.name, rel);
      await writeFileAtomic(p, content);
      files.push(p);
    }
  }
  for (const a of m.libraryAgents) {
    const p = join(agentsDir, `${a.name}.md`);
    await writeFileAtomic(p, a.content);
    files.push(p);
  }

  await writeJsonAtomic(stampPath, {
    namespace: m.namespace,
    user: m.user.id,
    assignments: m.assignments.map((a) => ({ purpose: a.purpose, scope: a.scope ?? null, role: a.role })),
  });
  files.push(stampPath);

  return { files };
}
