// Multi-harness workspace emission (ADR 0017).
//
// The resolver produces one neutral Manifest. Claude and Codex prepare native
// artifacts in memory; this orchestrator validates ownership, applies both
// builders as one transaction, and records exact per-builder inventories.

import { existsSync } from "node:fs";
import { lstat, readFile, readdir, rmdir, unlink } from "node:fs/promises";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { writeFileAtomic } from "../fs/atomic.ts";
import type { Artifact, BuilderName, Degradation } from "./artifacts.ts";
import { prepareClaude } from "./emit-claude.ts";
import { prepareCodex } from "./emit-codex.ts";
import type { Manifest } from "./resolve.ts";

export {
  buildClaudeMd,
  buildMcp,
  buildSettings,
  type McpJson,
  type SettingsJson,
  type SurrealAccess,
} from "./emit-claude.ts";
export { buildAgentsMd, buildCodexConfig } from "./emit-codex.ts";
import type { SurrealAccess } from "./emit-claude.ts";

const STAMP_PATH = ".merovingian/build.json";
const STAMP_SCHEMA = 2;
const BUILDER_VERSION = 1;

interface BuilderStamp {
  version: number;
  files: string[];
  degradations?: Degradation[];
}

export interface BuildStamp {
  schemaVersion: number;
  namespace: string;
  user: string;
  assignments: Array<{ purpose: string; scope: string | null; role: string }>;
  builders: Record<BuilderName, BuilderStamp>;
  plugins: Array<{
    id: string;
    claude?: { source: string; name: string };
    codex?: { source: string; name: string };
  }>;
}

interface LegacyStamp {
  namespace?: string;
  user?: string;
  assignments?: unknown[];
}

interface Snapshot {
  exists: boolean;
  content?: string;
  mode?: number;
}

export interface EmitResult {
  files: string[];
  degradations: Degradation[];
}

function safeRelativePath(path: string): string {
  const normalized = path.replaceAll("\\", "/");
  if (
    !normalized ||
    isAbsolute(path) ||
    normalized === ".." ||
    normalized.startsWith("../") ||
    normalized.includes("/../")
  ) {
    throw new Error(`unsafe generated path "${path}"`);
  }
  return normalized;
}

function absolutePath(targetDir: string, path: string): string {
  const target = resolve(targetDir);
  const absolute = resolve(target, safeRelativePath(path));
  const rel = relative(target, absolute);
  if (rel === ".." || rel.startsWith(`..${sep}`) || isAbsolute(rel)) {
    throw new Error(`generated path escapes workspace: "${path}"`);
  }
  return absolute;
}

async function filesUnder(root: string, prefix: string): Promise<string[]> {
  if (!existsSync(root)) return [];
  const out: string[] = [];
  for (const entry of await readdir(root, { withFileTypes: true })) {
    const absolute = join(root, entry.name);
    const rel = `${prefix}/${entry.name}`;
    if (entry.isDirectory()) out.push(...await filesUnder(absolute, rel));
    else out.push(rel);
  }
  return out;
}

async function previousOwnership(targetDir: string): Promise<{
  stamp?: BuildStamp | LegacyStamp;
  owned: Set<string>;
}> {
  const stampAbsolute = join(targetDir, STAMP_PATH);
  if (!existsSync(stampAbsolute)) return { owned: new Set() };
  let stamp: BuildStamp | LegacyStamp;
  try {
    stamp = JSON.parse(await readFile(stampAbsolute, "utf8")) as BuildStamp | LegacyStamp;
  } catch {
    throw new Error(`${STAMP_PATH} is not valid JSON — refusing to guess generated-file ownership`);
  }

  if ("schemaVersion" in stamp && stamp.schemaVersion === STAMP_SCHEMA && "builders" in stamp) {
    const owned = new Set<string>([STAMP_PATH]);
    for (const builder of Object.values(stamp.builders)) {
      for (const path of builder.files) owned.add(safeRelativePath(path));
    }
    return { stamp, owned };
  }

  // The pre-0017 emitter explicitly owned these Claude directories wholesale.
  // This one-time migration converts that broad ownership into an inventory.
  if (stamp.namespace && stamp.user) {
    const owned = new Set<string>([
      STAMP_PATH,
      "CLAUDE.md",
      ".mcp.json",
      ".claude/settings.local.json",
      ...await filesUnder(join(targetDir, ".claude", "skills"), ".claude/skills"),
      ...await filesUnder(join(targetDir, ".claude", "agents"), ".claude/agents"),
    ]);
    return { stamp, owned };
  }
  throw new Error(`${STAMP_PATH} is not a recognized Merovingian build stamp`);
}

function hasGeneratedMarker(path: string, content: string): boolean {
  if (path === "AGENTS.md" || path === "CLAUDE.md") {
    return content.includes("Scoped projection generated by `merovingian build`");
  }
  if (path === ".codex/config.toml" || path.startsWith(".codex/agents/")) {
    return content.startsWith("# Generated by merovingian build.");
  }
  return false;
}

async function assertOwnership(targetDir: string, artifacts: Artifact[], owned: Set<string>): Promise<void> {
  for (const artifact of artifacts) {
    const path = safeRelativePath(artifact.path);
    const absolute = absolutePath(targetDir, path);
    if (!existsSync(absolute) || owned.has(path)) continue;
    const stat = await lstat(absolute);
    if (!stat.isFile()) throw new Error(`${path} exists and is not a generated file`);
    const content = await readFile(absolute, "utf8");
    if (!hasGeneratedMarker(path, content)) {
      throw new Error(`${path} already exists and is not owned by Merovingian`);
    }
  }
}

async function assertSafeParents(targetDir: string, paths: string[]): Promise<void> {
  const target = resolve(targetDir);
  for (const path of paths) {
    const parts = safeRelativePath(path).split("/");
    let current = target;
    for (const part of parts.slice(0, -1)) {
      current = join(current, part);
      try {
        const stat = await lstat(current);
        if (!stat.isDirectory()) {
          throw new Error(`${relative(target, current)} is not a workspace directory`);
        }
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") break;
        throw error;
      }
    }
  }
}

function gitRootContaining(targetDir: string): string | undefined {
  let current = resolve(targetDir);
  while (true) {
    if (existsSync(join(current, ".git"))) return current;
    const parent = dirname(current);
    if (parent === current) return undefined;
    current = parent;
  }
}

function stampFor(m: Manifest, artifacts: Artifact[], degradations: Degradation[]): BuildStamp {
  const builders = Object.fromEntries(
    (["common", "claude", "codex"] as BuilderName[]).map((name) => {
      const builderDegradations = degradations.filter((d) => d.builder === name);
      return [
        name,
        {
          version: BUILDER_VERSION,
          files: artifacts.filter((a) => a.builder === name).map((a) => a.path).sort(),
          ...(builderDegradations.length ? { degradations: builderDegradations } : {}),
        },
      ];
    }),
  ) as Record<BuilderName, BuilderStamp>;

  return {
    schemaVersion: STAMP_SCHEMA,
    namespace: m.namespace,
    user: m.user.id,
    assignments: m.assignments.map((a) => ({
      purpose: a.purpose,
      scope: a.scope ?? null,
      role: a.role,
    })),
    builders,
    plugins: m.plugins.map((id) => {
      const at = id.lastIndexOf("@");
      const marketplace = id.slice(at + 1);
      const bindings = m.marketplaces[marketplace] ?? {};
      return {
        id,
        ...(bindings.claude ? { claude: bindings.claude } : {}),
        ...(bindings.codex ? { codex: bindings.codex } : {}),
      };
    }),
  };
}

async function snapshot(path: string): Promise<Snapshot> {
  if (!existsSync(path)) return { exists: false };
  const stat = await lstat(path);
  if (!stat.isFile()) throw new Error(`${path} is not a regular file`);
  return { exists: true, content: await readFile(path, "utf8"), mode: stat.mode & 0o777 };
}

async function restore(path: string, before: Snapshot): Promise<void> {
  if (!before.exists) {
    if (!existsSync(path)) return;
    try {
      await unlink(path);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
    return;
  }
  await writeFileAtomic(path, before.content ?? "", { mode: before.mode });
}

async function removeFile(path: string): Promise<void> {
  try {
    await unlink(path);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
}

async function pruneEmptyParents(targetDir: string, paths: string[]): Promise<void> {
  const target = resolve(targetDir);
  const dirs = [...new Set(paths.map((path) => dirname(absolutePath(target, path))))]
    .sort((a, b) => b.length - a.length);
  for (const start of dirs) {
    let current = start;
    while (current !== target && current.startsWith(`${target}${sep}`)) {
      try {
        await rmdir(current);
      } catch {
        break;
      }
      current = dirname(current);
    }
  }
}

async function applyTransaction(
  targetDir: string,
  artifacts: Artifact[],
  stale: string[],
): Promise<void> {
  const byPath = new Map(artifacts.map((artifact) => [artifact.path, artifact]));
  const touched = [...new Set([...byPath.keys(), ...stale])];
  const snapshots = new Map<string, Snapshot>();
  for (const path of touched) snapshots.set(path, await snapshot(absolutePath(targetDir, path)));

  const stamp = byPath.get(STAMP_PATH);
  try {
    for (const artifact of artifacts) {
      if (artifact.path === STAMP_PATH) continue;
      await writeFileAtomic(absolutePath(targetDir, artifact.path), artifact.content, { mode: artifact.mode });
    }
    for (const path of stale) await removeFile(absolutePath(targetDir, path));
    if (!stamp) throw new Error("internal error: build stamp artifact is missing");
    await writeFileAtomic(absolutePath(targetDir, STAMP_PATH), stamp.content, { mode: stamp.mode });
  } catch (error) {
    const rollbackErrors: unknown[] = [];
    for (const path of [...touched].reverse()) {
      try {
        await restore(absolutePath(targetDir, path), snapshots.get(path)!);
      } catch (rollbackError) {
        rollbackErrors.push(rollbackError);
      }
    }
    await pruneEmptyParents(targetDir, touched);
    if (rollbackErrors.length) {
      throw new AggregateError(
        [error, ...rollbackErrors],
        "workspace emission failed and could not be rolled back completely",
      );
    }
    throw error;
  }
  await pruneEmptyParents(targetDir, stale);
}

export async function emit(m: Manifest, targetDir: string, access?: SurrealAccess): Promise<EmitResult> {
  const target = resolve(targetDir);
  if (Object.keys(m.toolEnv).length) {
    const gitRoot = gitRootContaining(target);
    if (gitRoot) {
      throw new Error(
        `company secrets cannot be emitted inside a Git repository (${gitRoot}); ` +
          "build into a generated workspace outside Git",
      );
    }
  }

  const claude = prepareClaude(m, access);
  const codex = prepareCodex(m, access);
  const degradations = [...claude.degradations, ...codex.degradations];
  const artifacts: Artifact[] = [...claude.artifacts, ...codex.artifacts];
  const stamp = stampFor(m, [
    ...artifacts,
    { builder: "common", path: STAMP_PATH, content: "" },
  ], degradations);
  artifacts.push({
    builder: "common",
    path: STAMP_PATH,
    content: JSON.stringify(stamp, null, 2) + "\n",
    mode: 0o600,
  });

  const { owned } = await previousOwnership(target);
  const next = new Set(artifacts.map((artifact) => artifact.path));
  const stale = [...owned].filter((path) => path !== STAMP_PATH && !next.has(path)).sort();
  await assertSafeParents(target, [...artifacts.map((artifact) => artifact.path), ...stale]);
  await assertOwnership(target, artifacts, owned);
  await applyTransaction(target, artifacts, stale);

  return {
    files: artifacts.map((artifact) => absolutePath(target, artifact.path)),
    degradations,
  };
}
