import { assignmentsLabel, type Manifest } from "./resolve.ts";
import type { Degradation } from "./artifacts.ts";

export type Harness = "claude" | "codex";

/** Shared semantic renderer. Harness-specific paths are the only differences;
 * the projected identity, capabilities, and delegation contract stay identical. */
export function buildWorkspaceInstructions(
  m: Manifest,
  harness: Harness,
  degradations: Degradation[] = [],
): string {
  const rootFile = harness === "claude" ? "CLAUDE.md" : "AGENTS.md";
  const skillDir = harness === "claude" ? ".claude/skills/" : ".agents/skills/";
  const agentDir = harness === "claude" ? ".claude/agents/" : ".codex/agents/";
  const lines: string[] = [];
  lines.push(`# ${m.namespace} — workspace of ${m.user.name}`);
  lines.push("");
  lines.push(
    `> Scoped projection generated by \`merovingian build\`. ` +
      `Assignments: **${assignmentsLabel(m.assignments)}**` +
      `. Do not edit ${rootFile} by hand — run the build again.`,
  );
  lines.push("");

  if (harness === "codex") {
    lines.push("## First use in Codex");
    lines.push(
      "Trust this workspace when Codex asks. Until it is trusted, Codex deliberately ignores " +
        "the projected `.codex/config.toml`, including MCP servers and read-only OKF permissions.",
    );
    lines.push("");
  }

  lines.push("## Delegation");
  lines.push(
    "Work in the main session by default. When a request clearly belongs to a visible purpose with an agent, " +
      "delegate it to that subagent. Use the `route` skill for ambiguous or composite requests.",
  );
  lines.push("");

  lines.push("## Purposes");
  if (m.visiblePurposes.length) {
    const agents = new Map(m.purposeAgents.map((a) => [a.purpose, a.agent]));
    lines.push(
      m.visiblePurposes
        .map((purpose) => `- \`${purpose}\`${agents.has(purpose) ? ` → subagent \`${agents.get(purpose)}\`` : ""}`)
        .join("\n"),
    );
  } else {
    lines.push("_(none)_");
  }
  lines.push("");

  lines.push("## Skills");
  const skills = [...m.ambientSkills.map((s) => `${s} (ambient)`), ...m.skills];
  lines.push(skills.length ? skills.map((s) => `\`${s}\``).join(" · ") : "_(none)_");
  lines.push("");

  lines.push("## Tools");
  lines.push(m.tools.length ? m.tools.map((t) => `\`${t}\``).join(" · ") : "_(none)_");
  lines.push("");

  lines.push("## Context (okf — read-only mounts)");
  lines.push(m.okf.length ? m.okf.map((o) => `- \`${o.bucket}\` → \`${o.path}\``).join("\n") : "_(none)_");
  lines.push("");

  lines.push("## Data (surreal — via scoped MCP)");
  lines.push(
    m.surreal.length
      ? m.surreal
          .map((s) => `- \`${s.bucket}\` [${s.tables.join(", ")}]${s.scope ? ` — scope \`${s.scope}\`` : ""}`)
          .join("\n")
      : "_(none)_",
  );
  lines.push("");

  lines.push("## Decisions (via the decisions MCP)");
  lines.push(
    m.decisionDomains.length
      ? `Your decision domains: ${m.decisionDomains.map((d) => `\`${d}\``).join(" · ")}.`
      : `_(no decision domains on your purposes)_`,
  );
  lines.push("");
  lines.push(
    `**Records are law; logs are jurisprudence under construction.** Ratified records ` +
      `(\`search-decisions\`/\`get-decision\`) are universal and binding. In-flight logs you or ` +
      `others registered are NOT policy — never apply one without confirming with your human. ` +
      `When you make a call mid-work that no record covers, \`register-decision\` it (with the ` +
      `records you applied, if any) — governance drains the log and promotes what converges.`,
  );
  lines.push("");

  lines.push(`## Library (materialized for ${harness})`);
  if (m.librarySkills.length || m.libraryAgents.length) {
    if (m.librarySkills.length) {
      lines.push(`- skills: ${m.librarySkills.map((s) => `\`${s.name}\``).join(" · ")} → \`${skillDir}\``);
    }
    if (m.libraryAgents.length) {
      lines.push(`- agents: ${m.libraryAgents.map((a) => `\`${a.name}\``).join(" · ")} → \`${agentDir}\``);
    }
  } else {
    lines.push("_(none)_");
  }
  lines.push("");

  lines.push("## Plugins (external)");
  lines.push(m.plugins.length ? m.plugins.map((p) => `- \`${p}\``).join("\n") : "_(none)_");
  lines.push("");

  const relevant = degradations.filter((d) => d.builder === harness);
  if (relevant.length) {
    lines.push("## Unavailable capabilities");
    for (const d of relevant) {
      lines.push(`- \`${d.resource}\` (${d.capability}): ${d.reason}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}
