// The domain-schema GENERATOR (ADR 0011): the engine never ships a tenant's business
// tables — it derives them from the graph. For every `backend: surreal` bucket in the
// Definition, emit DEFINE TABLE + PERMISSIONS for each of its tables:
//
//   FOR select WHERE
//     <rowScope> IN $auth->responsible.scope                      -- scoped path
//     OR $auth->responsible[WHERE scope = NONE]->purpose
//        CONTAINSANY bucket:⟨<id>⟩.owner.lineage                  -- unscoped/ancestry path
//   FOR create, update, delete NONE;                              -- writes = root only (today)
//
// Security-critical: this is the ONLY author of domain PERMISSIONS. It is a pure
// string generator (PERMISSIONS clauses cannot be parameterized), so identifiers are
// validated here AND in validateGraph (defense in depth). Idempotent OVERWRITE —
// regenerated on every apply; never diffs, never DROPs (a removed bucket orphans its
// tables + data; removal is a manual, human act).
//
// Preserved semantics (byte-identical to the old hand-written client template) — two
// known quirks are INTENTIONAL here and future-ADR material; do not "fix" in passing:
//   (a) the unscoped path checks only the bucket OWNER's lineage: a purpose that
//       merely `reads` the bucket gets the projection mount, but its unscoped members
//       are blocked by the db (db stricter than projection = fail-closed, safe);
//   (b) scope VALUES match globally: any assignment scoped "north" sees rows with
//       <rowScope> = "north" in ANY bucket sharing that rowScope field.
//
// TODO (kept from the old data.surql): ancestry uses the denormalized purpose.lineage
// (computed in TS at apply). The elegant path is a live recursive traversal in
// SurrealQL (3.x recursive paths) — flat was chosen for safety; worth proving later.

import type { Bucket, Definition } from "../provider/types.ts";

/** Table + field identifiers — interpolated RAW into DDL. Strict on purpose. */
export const SURREAL_IDENT = /^[A-Za-z_][A-Za-z0-9_]{0,63}$/;

/** Bucket ids are slugs (hyphens legal — interpolated ⟨escaped⟩ as record ids). */
export const BUCKET_ID = /^[A-Za-z0-9_-]{1,64}$/;

/** Engine tables a tenant bucket may NEVER claim — the generator would OVERWRITE
 *  their permissions. Keep in sync with surreal/schema.surql + data.surql. */
export const RESERVED_TABLES = new Set([
  "config", "purpose", "bucket", "tool", "marketplace", "skill", "agent", "user", "responsible", "inbox",
  "decision", "decision_log", "decision_domain",
]);

function assertSafe(b: Bucket): void {
  if (!BUCKET_ID.test(b.id)) throw new Error(`domainSchema: unsafe bucket id "${b.id}"`);
  if (b.rowScope !== undefined && !SURREAL_IDENT.test(b.rowScope)) {
    throw new Error(`domainSchema: unsafe rowScope "${b.rowScope}" on bucket "${b.id}"`);
  }
  for (const t of b.tables ?? []) {
    if (!SURREAL_IDENT.test(t)) throw new Error(`domainSchema: unsafe table name "${t}" on bucket "${b.id}"`);
    if (RESERVED_TABLES.has(t)) throw new Error(`domainSchema: table "${t}" is reserved (engine table)`);
  }
}

/** One DDL statement block per table of every surreal bucket, Definition order.
 *  Pure — snapshot-tested by exact string. */
export function domainSchema(def: Definition): string[] {
  const out: string[] = [];
  for (const b of def.buckets) {
    if (b.backend !== "surreal") continue;
    assertSafe(b);
    // ⟨⟩-escaped record id: hyphenated bucket ids (e.g. faturamento-e-financas) stay legal.
    const ownerLineage = `bucket:⟨${b.id}⟩.owner.lineage`;
    const unscoped = `$auth->responsible[WHERE scope = NONE]->purpose CONTAINSANY ${ownerLineage}`;
    for (const t of b.tables ?? []) {
      const select = b.rowScope
        ? `${b.rowScope} IN $auth->responsible.scope\n      OR ${unscoped}`
        : unscoped;
      let ddl =
        `-- generated by merovingian (ADR 0011) — bucket "${b.id}"; regenerated on every apply, do not hand-edit\n` +
        `DEFINE TABLE OVERWRITE ${t} SCHEMALESS\n` +
        `  PERMISSIONS\n` +
        `    FOR select WHERE\n` +
        `      ${select}\n` +
        `    FOR create, update, delete NONE;`;
      if (b.rowScope) {
        ddl += `\nDEFINE FIELD OVERWRITE ${b.rowScope} ON ${t} TYPE option<string>;`;
      }
      out.push(ddl);
    }
  }
  return out;
}
